### ISSUE TITLE
Add comments to the Class and methods to explain what they do

### ISSUE THREAD

**Issue by kulloveth** [angiejones/java-programming#5]
## Add Comments to the class and JavaDoc to methods to explain what they do

@angiejones  can I work on this?

**Comment by anushka530** [comment]
It will be great to solve this issue. Please assign this issue to me.

**Comment by angiejones** [comment]
No thank you. The code is in sync with the videos. Adding additional comments will get it out of synch and line numbers won't match from what the students are viewing/creating.

All commentary is in the videos
